name: Server Tests

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'content/**'
      - 'api/**'
      - 'server/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'content/**'
      - 'api/**'
      - 'server/**'

jobs:
  test:
    name: Test server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
        architecture: x86
    - uses: gradle/wrapper-validation-action@v1
    - uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: 5.2.1
    - run: gradle wrapper && ./gradlew test
      working-directory: server
